FIRST_BYTE = 0x1
IDLE = 0x1
ACTIVE = 0x2
RECHARGE = 0x3
ENDIAN = 'little'

PACKET_BEGINING = '=BH8sBB8s'
PACKET_END_WITH_VALUE = '=Lc'
PACKET_END_WITHOUT_VALUE = 'c'

RESPONSE_SUCCESS = 0x11
RESPONSE_FAIL = 0x12
RESPONSE_FORMAT = '=BH'
